export const onlineClassesSubcategories = [
  "One-on-One Tutoring",
  "Group Classes",
  "Workshops",
  "Webinars",
  "Masterclasses",
  "Live Q&A Sessions",
  "Interactive Courses",
  "Virtual Classroom",
  "Live Online Tuition Classes",
  "Recorded Online Courses",
  "Interactive Virtual Classes",
  "One-on-One Online Tutoring",
  "Group Online Learning Sessions",
  "Online Language Classes",
  "Online Hobby Classes",
  "Online IT Certification Courses",
  "Online Exam Preparation",
  "Online University Courses",
  "Online Skill Development",
  "Online Professional Training",
  "Online Coding Bootcamps",
  "Online Music Lessons",
  "Online Art Classes",
  "Online Yoga & Fitness",
  "Online Business Courses",
  "Online STEM Education",
  "Online Test Series",
  "Online Doubt Solving Sessions",
  "Webinar-based Learning",
  "Online Project-based Learning",
  "Online Internship Programs",
  "Online Certification Programs",
  "Online Workshop Sessions",
  "Nursery-KG Tuition",
  "Class I-V Tuition",
  "Class 6 Tuition",
  "Class 7 Tuition",
  "Class 8 Tuition",
  "Class 9 Tuition",
  "Class 10 Tuition",
  "Class 11 Tuition",
  "Class 12 Tuition",
  "BTech Tuition",
  "BSc Tuition",
  "BCom Tuition",
  "BA Tuition",
  "Engineering Diploma Tuition",
  "BCA Tuition",
  "BBA Tuition",
  "MBBS & Medical Tuition",
  "LLB Tuition",
  "MSc Tuition",
  "Pharmacy Tuition",
  "MBA Tuition",
  "B Ed Tuition",
  "MA Tuition",
  "MCom Tuition",
  "MTech Tuition",
  "BMS Tuition",
  "Dental Tuition",
  "BAF Tuition",
  "Bachelor of Ayurvedic Medicine and Surgery Tuition",
  "Bachelor of Homeopathic Medicine and Surgery, Physiotherapy and Occupational Therapy Tuition",
  "BFA Tuition",
  "BFM tuition",
  "BBI Tuition",
  "DNB Medicine Tuition",
  "IIT JEE Coaching",
  "NEET Coaching",
  "UPSC Civil Services",
  "GATE Coaching",
  "CAT Coaching",
  "GMAT Coaching",
  "GRE Coaching",
  "TOEFL Coaching",
  "IELTS Coaching",
  "SAT Coaching",
  "Bank PO Coaching",
  "SSC CGL Coaching",
  "Railway Exams Coaching",
  "Defense Exams Coaching",
  "CLAT Coaching",
  "CA Foundation",
  "CS Professional",
  "CMA Coaching",
  "NDA Coaching",
  "CDS Coaching",
  "AFCAT Coaching",
  "CTET Coaching",
  "NET Coaching",
  "SET Coaching",
  "Medical Entrance Exams",
  "Engineering Entrance Exams",
  "Law Entrance Exams",
  "Design Entrance Exams",
  "Management Entrance Exams",
  "Civil Services Prelims",
  "Civil Services Mains",
  "State PSC Exams",
  "Insurance Exams",
  "Teaching Exams",
  "Hotel Management Exams",
  "Fashion Technology Exams",
  "Company Secretary Exams",
  "Chartered Accountancy Exams",
  "Cost Accounting Exams",
  "Actuarial Science Exams",
   "Spoken English",
  "French Language",
  "Hindi Language",
  "German Language",
  "Spanish Language",
  "Japanese Language",
  "Kannada Language",
  "Arabic Language",
  "Phonics",
  "Chinese Language",
  "Tamil Language",
  "Telugu Language",
  "Sanskrit Language",
  "Korean Language",
  "Marathi Speaking",
  "Russian Language",
  "Italian Language",
  "Malayalam Speaking",
  "Bengali Speaking",
  "Urdu language",
  "Accent Training Classes",
  "Gujarati Speaking",
  "Dutch Language",
  "Punjabi Speaking",
  "Portuguese Language",
  "Swedish Language",
  "Persian Language",
  "Language translation services",
  "Thai Language",
  "Elocution",
  "Turkish Language",
  "Danish Language",
  "Filipino",
  "Sinhala language",
  "Balochi language",
  "Polish Language",
  "Hungarian Language",
  "Slovenian Language",
];
export const tuitionSubcategories = [
  "Nursery-KG Tuition",
  "Class I-V Tuition",
  "Class 6 Tuition",
  "Class 7 Tuition",
  "Class 8 Tuition",
  "Class 9 Tuition",
  "Class 10 Tuition",
  "Class 11 Tuition",
  "Class 12 Tuition",
  "BTech Tuition",
  "BSc Tuition",
  "BCom Tuition",
  "BA Tuition",
  "Engineering Diploma Tuition",
  "BCA Tuition",
  "BBA Tuition",
  "MBBS & Medical Tuition",
  "LLB Tuition",
  "MSc Tuition",
  "Pharmacy Tuition",
  "MBA Tuition",
  "B Ed Tuition",
  "MA Tuition",
  "MCom Tuition",
  "MTech Tuition",
  "BMS Tuition",
  "Dental Tuition",
  "BAF Tuition",
  "Bachelor of Ayurvedic Medicine and Surgery Tuition",
  "Bachelor of Homeopathic Medicine and Surgery, Physiotherapy and Occupational Therapy Tuition",
  "BFA Tuition",
  "BFM tuition",
  "BBI Tuition",
  "DNB Medicine Tuition",
];
export const languageSubcategories = [
  "Spoken English",
  "French Language",
  "Hindi Language",
  "German Language",
  "Spanish Language",
  "Japanese Language",
  "Kannada Language",
  "Arabic Language",
  "Phonics",
  "Chinese Language",
  "Tamil Language",
  "Telugu Language",
  "Sanskrit Language",
  "Korean Language",
  "Marathi Speaking",
  "Russian Language",
  "Italian Language",
  "Malayalam Speaking",
  "Bengali Speaking",
  "Urdu language",
  "Accent Training Classes",
  "Gujarati Speaking",
  "Dutch Language",
  "Punjabi Speaking",
  "Portuguese Language",
  "Swedish Language",
  "Persian Language",
  "Language translation services",
  "Thai Language",
  "Elocution",
  "Turkish Language",
  "Danish Language",
  "Filipino",
  "Sinhala language",
  "Balochi language",
  "Polish Language",
  "Hungarian Language",
  "Slovenian Language",
];
export const hobbySubcategories = [
  "Guitar Classes",
  "Piano Classes",
  "Violin Classes",
  "Dance Classes",
  "Yoga Classes",
  "Art & Craft Classes",
  "Painting Classes",
  "Photography Classes",
  "Pottery Classes",
  "Chess Coaching",
  "Cooking Classes",
  "Baking Classes",
  "Singing Classes",
  "Acting & Drama Classes",
  "Calligraphy Classes",
  "Origami Classes",
  "Knitting & Crochet Classes",
  "Gardening Classes",
  "Fitness Training",
  "Martial Arts Classes",
  "Sketching Classes",
  "Zumba Classes",
  "Mehendi Classes",
  "Tattoo Designing",
  "Jewelry Making Classes",
  "Candle Making Classes",
  "Floral Arrangement Classes",
  "Interior Design Classes",
  "Fashion Design Classes",
  "Makeup & Beauty Classes",
  "Nail Art Classes",
  "Hair Styling Classes",
  "DIY Craft Classes",
  "Woodworking Classes",
  "Glass Painting Classes",
  "Quilling Classes",
  "Embroidery Classes",
  "Sewing Classes",
  "Sketching & Drawing Classes",
  "Digital Art Classes",
];
export const itCoursesSubcategories = [
  "Python Programming",
  "Java Programming",
  "C++ Programming",
  "JavaScript Programming",
  "Web Development",
  "Mobile App Development",
  "Data Science",
  "Machine Learning",
  "Artificial Intelligence",
  "Cloud Computing",
  "Cyber Security",
  "Ethical Hacking",
  "Blockchain Technology",
  "Full Stack Development",
  "Frontend Development",
  "Backend Development",
  "React JS",
  "Angular JS",
  "Node JS",
  "Django Framework",
  "Flask Framework",
  "Spring Framework",
  "Android Development",
  "iOS Development",
  "Flutter Development",
  "React Native",
  "Database Management",
  "SQL",
  "MongoDB",
  "DevOps",
  "AWS Certification",
  "Azure Certification",
  "Google Cloud Certification",
  "UI/UX Design",
  "Graphic Design",
  "Adobe Photoshop",
  "Adobe Illustrator",
  "Adobe Premiere Pro",
  "Video Editing",
  "3D Animation",
  "Game Development",
  "Unity 3D",
  "Unreal Engine",
  "Data Structures & Algorithms",
  "Competitive Programming",
  "Software Testing",
  "Quality Assurance",
  "Agile & Scrum",
  "ITIL Certification",
  "Big Data & Hadoop",
];
export const examCoachingSubcategories = [
  "IIT JEE Coaching",
  "NEET Coaching",
  "UPSC Civil Services",
  "GATE Coaching",
  "CAT Coaching",
  "GMAT Coaching",
  "GRE Coaching",
  "TOEFL Coaching",
  "IELTS Coaching",
  "SAT Coaching",
  "Bank PO Coaching",
  "SSC CGL Coaching",
  "Railway Exams Coaching",
  "Defense Exams Coaching",
  "CLAT Coaching",
  "CA Foundation",
  "CS Professional",
  "CMA Coaching",
  "NDA Coaching",
  "CDS Coaching",
  "AFCAT Coaching",
  "CTET Coaching",
  "NET Coaching",
  "SET Coaching",
  "Medical Entrance Exams",
  "Engineering Entrance Exams",
  "Law Entrance Exams",
  "Design Entrance Exams",
  "Management Entrance Exams",
  "Civil Services Prelims",
  "Civil Services Mains",
  "State PSC Exams",
  "Insurance Exams",
  "Teaching Exams",
  "Hotel Management Exams",
  "Fashion Technology Exams",
  "Company Secretary Exams",
  "Chartered Accountancy Exams",
  "Cost Accounting Exams",
  "Actuarial Science Exams",
];
// const onlineClassesSubcategories = [
//   "Live Online Tuition Classes",
//   "Recorded Online Courses",
//   "Interactive Virtual Classes",
//   "One-on-One Online Tutoring",
//   "Group Online Learning Sessions",
//   "Online Language Classes",
//   "Online Hobby Classes",
//   "Online IT Certification Courses",
//   "Online Exam Preparation",
//   "Online University Courses",
//   "Online Skill Development",
//   "Online Professional Training",
//   "Online Coding Bootcamps",
//   "Online Music Lessons",
//   "Online Art Classes",
//   "Online Yoga & Fitness",
//   "Online Business Courses",
//   "Online STEM Education",
//   "Online Test Series",
//   "Online Doubt Solving Sessions",
//   "Webinar-based Learning",
//   "Online Project-based Learning",
//   "Online Internship Programs",
//   "Online Certification Programs",
//   "Online Workshop Sessions",
// ];
